### ISSUE TITLE
Runtime_engine下run programme的时候test_image.bin是在哪里生成的？

### ISSUE THREAD

**Issue by affectionlu** [TF2-Engine/TF2#17]
./bin/host ../host/model/googlenet/param.bin ../host/model/googlenet_Q ../host/test_images/googlenet_data_label_391.bin 1
 1）其中googlenet_data_label_391.bin 1是如何生成的？因为想用自己的图片测试，不知道如何生成。
 2）cnn/srs/test_images有两个.bin文件，但是我没有在代码库中找到生成代码文件。

**Comment by affectionlu** [comment]
@TF2-Engine

**Comment by TF2-Engine** [comment]
test_image.bin is for debugging. Specifically, it is for verfification of inference errors of each layer. The code to generate it is not complicated ( mainly about preprocessing and storing ) but we did not  release it. If you just want to try another image, you can use the imagenet_pyresnet50 branch which include the OpenCV library so that you can try any image in jpeg format. If you have the special demand to create another image.bin for debugging, please explain the necessity and we will try to help.

**Comment by affectionlu** [comment]
@TF2-Engine Thanks! I will try the method you recommended.
